In [11]:
"""Write a Python Program to Generate numbers from 100 to 1 only odd numbers"""
i=100
while(i>0):
   if i%2!=0:
    print("  ",i)
   i=i-1

   99
   97
   95
   93
   91
   89
   87
   85
   83
   81
   79
   77
   75
   73
   71
   69
   67
   65
   63
   61
   59
   57
   55
   53
   51
   49
   47
   45
   43
   41
   39
   37
   35
   33
   31
   29
   27
   25
   23
   21
   19
   17
   15
   13
   11
   9
   7
   5
   3
   1

In [3]:
"""Write a Python Program to Generate numbers from 1 to 100 only even numbers"""
for i in range(1,101):
  if i%2==0:
    print("  ",i)

   2
   4
   6
   8
   10
   12
   14
   16
   18
   20
   22
   24
   26
   28
   30
   32
   34
   36
   38
   40
   42
   44
   46
   48
   50
   52
   54
   56
   58
   60
   62
   64
   66
   68
   70
   72
   74
   76
   78
   80
   82
   84
   86
   88
   90
   92
   94
   96
   98
   100

In [4]:
"""Write a Python Program to Generate numbers from 10 to 50 and Add all the
Generated Numbers"""
sum=0
for i in range(10,51):
  print("  ",i)
  sum +=i

print("Total sum: ",sum)

   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
   20
   21
   22
   23
   24
   25
   26
   27
   28
   29
   30
   31
   32
   33
   34
   35
   36
   37
   38
   39
   40
   41
   42
   43
   44
   45
   46
   47
   48
   49
   50
Total sum:  1230

In [18]:
"""Get a Number from User to Display Table of that Number using While Loop."""
num=int(input("Enter a Number: "))
i=2
print(f"The divisors of {num} are:")
while(i<num):
  if num%i==0:
    print(i)
  i=i+1

Enter a Number: 22
The divisors of 22 are:
2
11

In [31]:
"""Get Starting and Ending Numbers from User to Generate a Sequence of Number. You Should Check at First, Starting
 Number should be Less Than Ending Number."""
start1=int(input("Enter start number:"))
end1=int(input("Enter start number:"))
if start1<end1:
  print("Ending Number is bigger than start number and the sequnce are: ")
  while(start1<=end1):
   print(start1)
   start1= start1 + 1
else:
  print("Ending Number is less than start number")

Enter start number:9
Enter start number:2
Ending Number is less than start number

In [20]:
"""Generate Odd Numbers From 1 to 20 and Generate Even Numbers from 20 to
1. And then add Both Results to Each Other. Total Result Should Display."""
i=1
sum1=0
sum2=0
while(i<20):
   if i%2!=0:
    print("  ",i)
    sum1=sum1+i
   i=i+1
while(i>0):
   if i%2==0:
    print("  ",i)
    sum1=sum1+i

   i=i-1
print("Total sum",sum1)

   1
   3
   5
   7
   9
   11
   13
   15
   17
   19
   20
   18
   16
   14
   12
   10
   8
   6
   4
   2
Total sum 210